image: mcr.microsoft.com/dotnet/sdk:3.1

stages:
  - build

before_script:
  - "dotnet restore"
  - "cp src/Credentials.cs.example src/Credentials.cs"

build:
  stage: build
  script:
    - "dotnet build"
