image: mcr.microsoft.com/dotnet/sdk:3.1

stages:
  - build
  - deploy

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - obj

before_script:
  - "dotnet restore"

buildDebug:
  stage: build
  script:
    - "dotnet build"
  artifacts:
    paths:
      - bin/Debug
    expire_in: 3 days

buildRelease:
  stage: build
  retry: 1
  script:
    - "dotnet build --configuration Release"
  artifacts:
    paths:
      - bin/Release

deploy:
  image: kroniak/ssh-client
  stage: deploy
  when: manual
  dependencies: ["buildRelease"]
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PROD_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no statty@jvyden.xyz ./init-deploy.sh
    - scp -o StrictHostKeyChecking=no -r bin/Release statty@jvyden.xyz:~/Statty
    - ssh -o StrictHostKeyChecking=no statty@jvyden.xyz ./finish-deploy.sh
  environment:
    name: production