image: mcr.microsoft.com/dotnet/sdk:3.1

stages:
  - build

before_script:
  - "dotnet restore"
  - "cp src/Credentials.cs.example src/Credentials.cs"

buildDebug:
  stage: build
  script:
    - "dotnet build"
  artifacts:
    paths:
      - bin/Debug
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - obj
      - bin

buildRelease:
  stage: build
  script:
    - "dotnet build --configuration Release"
  artifacts:
    paths:
      - bin/Release
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - obj
      - bin
